### ISSUE TITLE
mmvec installation

### ISSUE THREAD

**Issue by nzarnaghi** [biocore/mmvec#122]
Hi,

I want to install your mmvec on my desktop computer, but when I try "pip install mmvec", it shows the following error message:

Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-MChPLG/biom-format/

I also tried "conda install mmvec -c conda-forge", but it also shows the following error:

conda: command not found

Does anyone know how I can fix this?

**Comment by mortonjt** [comment]
Hi @nzarnaghi , I'll need more information on the pip error.  Can you print out  `which pip` and `python -v`?  Also, are you using [virtualenv](https://virtualenv.pypa.io/en/latest/)?  That'll make the pip install easier.

Regarding the conda error, its clear that you don't have conda installed.  See these instructions [here](https://docs.conda.io/en/latest/miniconda.html) and let me know if this will resolve your problems.

**Comment by nzarnaghi** [comment]
@mortonjt Thank you so much. I installed Miniconda and it is solved now.

**Comment by mortonjt** [comment]
great!
