### ISSUE TITLE
Running an example

### ISSUE THREAD

**Issue by nzarnaghi** [biocore/mmvec#123]
Hi,

I want to run the example provided below:

mmvec paired-omics \
	--microbe-file examples/cf/otus_nt.biom \
	--metabolite-file examples/cf/lcms_nt.biom \
	--summary-dir summary

But after running these commands, it shows the following error at the end:

TypeError: SparseDataFrame() takes no arguments

In addition, when I run tensorboard --logdir . , it shows the following error at the end:

ValueError: Duplicate plugins for name projector

Could you please guide me what might be the problem?

**Comment by mortonjt** [comment]
It looks like pandas 1.0 has made some breaking changes to biom.  See here: https://github.com/biocore/biom-format/issues/837

The solution for now is to run
`conda install pandas<1.0`

Just merged in a PR here: https://github.com/conda-forge/mmvec-feedstock/pull/7
So a more permanent solution is in the works

**Comment by nzarnaghi** [comment]
Hi 

Thank you so much. I tried 

conda install pandas<1.0

But now, it shows this error:

bash: 1.0: No such file or directory

**Comment by mortonjt** [comment]
Sorry, that was a typo - that should be `conda install pandas=0.24`

But the conda install should be working now, so feel free to retry the original install instructions.

**Comment by nzarnaghi** [comment]
Thank you so much. It worked now.

**Comment by mortonjt** [comment]
great!
