### ISSUE TITLE
How can I get the exact feature id and otu id in heatmap, correspondingly.

### ISSUE THREAD

**Issue by ChangkunLi2019** [biocore/mmvec#124]
Recently I have some problems with using mmvec. When I got the heatmap result , I don't known how to get the exact feature id and otu id of  the large positive values. The lables of id were incomplete in the heatmap. How can I map metabolites and bacteria one by one?

![搜狗截图20年02月25日2233_1](https://user-images.githubusercontent.com/52815918/75256745-e6a41e80-581e-11ea-9491-7ca79ce2b96b.png)
![搜狗截图20年02月25日2234_2](https://user-images.githubusercontent.com/52815918/75256819-0b989180-581f-11ea-9178-c6122774f539.png)

**Comment by mortonjt** [comment]
Hi @ChangkunLi2019 , can you list the exact commands that you ran? Did you use `heatmap` or `paired-heatmap`? Note the heatmap is meant for high-level visualization, not for this sort of task.

There are commands to extract the ranks in the README with the `tabulate` command.

**Comment by ChangkunLi2019** [comment]
qiime metadata tabulate --m-input-file conditionals.qza --o-visualization conditionals-viz.qzv

qiime mmvec heatmap --i-ranks ranks.qza --m-microbe-metadata-file taxonomy.tsv --m-microbe-metadata-column Taxon  --m-metabolite-metadata-file metabolite-metadata.txt --m-metabolite-metadata-column Compound_Source --p-level 5 --o-visualization ranks-heatmap.qzv

Thank you very much ! There are some error？I want to know what metabolites and bacteria correspond in the data table, but I am failure. 
![搜狗截图20年02月26日0923_1](https://user-images.githubusercontent.com/52815918/75302742-b178ea00-5879-11ea-9abe-0da8884e2662.png)

**Comment by mortonjt** [comment]
@ChangkunLi2019 the latest heatmap looks fine -- you should be able to sort the metabolites for each microbe in `conditionals-viz.qzv`.  You can also import these files into excel for you own viewing.
