### ISSUE TITLE
convert CF simulation data to biom

### ISSUE THREAD

**Issue by nzarnaghi** [biocore/mmvec#126]
Hi,

When I created CF simulation data using the following link, 

https://github.com/zhangzhongxun/WinCF_model_Code

there are many txt files generated, like F_0, F_1,I-0, I-1, I_2, ... How can I combine all of these files to generate a single microbe biom file and a single metabolite biom file?

Thank you,

**Comment by mortonjt** [comment]
There are ipython notebooks in https://github.com/knightlab-analyses/multiomic-cooccurrences
If you have questions, on those - feel free to open issues there.

But please carefully read the code first.
