### ISSUE TITLE
heatmap missing some in row and column

### ISSUE THREAD

**Issue by LiZhihua1982** [biocore/mmvec#143]
Dear author,
I think there should some otu be shown between Zotu139 and Zotu171 in the column. However, it is missing? 
![heatmap](https://user-images.githubusercontent.com/38903973/87783329-34bdcb00-c86f-11ea-8620-849e423fa293.png)

Best regards

Li Zhihua

**Comment by mortonjt** [comment]
That is expected - since heatmaps won't be able to display all of the information (there aren't enough pixels to view most of these files).
