### ISSUE TITLE
heatmap in svg format

### ISSUE THREAD

**Issue by khemlalnirmalkar** [biocore/mmvec#146]
Hi @mortonjt ,
![heatmap](https://user-images.githubusercontent.com/32944151/92463883-3b870100-f181-11ea-98e7-d2698affe775.JPG)

If you see my heatmap, log scale and metabolite names are interfering with each other. Since qiime2 view is giving me only PDF format to save, i can't edit it. Is there any way to save it in an SVG format? i couldn't find the option.
Thanks,

**Comment by mortonjt** [comment]
PDFs should not be the problem - perhaps it is best to post on the qiime2
forums for this sort of question (since it'll be useful for others).

**Comment by khemlalnirmalkar** [comment]
![heatmap2](https://user-images.githubusercontent.com/32944151/92492867-b6174700-f1a8-11ea-9924-23adc1278274.JPG)
if you see the log scale and metabolite names, they are merging, that's the problem with  PDFs and cant edit it,
Thanks, i will ask in the qiime2 forum,

**Comment by mortonjt** [comment]
Hi @khemlalnirmalkar see issue #156, since exporting the file to be processed in Python / R may be the way to address this issue.
