### ISSUE TITLE
Normality test for relative abundance data

### ISSUE THREAD

**Issue by khemlalnirmalkar** [biocore/mmvec#147]
Hi @mortonjt ,

Do we need to do normality tests of bacteria/pathways (relative abundance)?
if yes/no why?

My apologies, the question is not related to mmvec, but I realized you are very good in statistics.
I thought, your expertise can help me to solve this confusion.
Thanks,
Khem

**Comment by mortonjt** [comment]
No, microbiome data is not normal

**Comment by khemlalnirmalkar** [comment]
do you mean the distribution of microbiota data is not normal?

**Comment by mortonjt** [comment]
yes.

Its best to report these types of questions on the qiime2 forums -- this issue tracker is reserved for issues running MMvec.

**Comment by khemlalnirmalkar** [comment]
Thanks for your quick response,
Yes, i will use qiime2 forum for the next time. My apologies,
