### ISSUE TITLE
Tensorflow numpy incompatible with Qiime 2020.8 (current version)

### ISSUE THREAD

**Issue by afvrbanac** [biocore/mmvec#148]
Breaks the Qiime2 conda environment after installing as it cannot refresh the cache. Appears to be an issue with numpy.

Warning/error when installing:

tensorflow 1.15.4 requires numpy<1.19.0,>=1.16.0, but you'll have numpy 1.19.1 which is incompatible.

End of error message when refreshing the cache:

raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (numpy 1.19.1 (/Users/avrbanac/miniconda3/envs/qiime2-2020.8/lib/python3.6/site-packages), Requirement.parse('numpy<1.19.0,>=1.16.0'), {'tensorflow'})

**Comment by mortonjt** [comment]
Thanks @afvrbanac for bringing this up.

Unfortunately all paths lead to complete rewrites; either upgrade everything to TF2 (a sure path of thorns), or rewrite everything in pytorch...

We do have an upcoming MMvec2 with a ton more features.  So perhaps that will be the solution to these problems.

**Comment by afvrbanac** [comment]
I ended up abandoning the Q2 install just using the standalone version, but also had to wrestle with that to get it installed, and I'm still not entirely sure if it's working correctly (do you ever get very high cv-rsme? It still exponentially decays and plateaus). Glad to hear about mmvec2 though! Any rough estimate of when that might be out? I may just abandon this analysis until then..

**Comment by mortonjt** [comment]
It'll be a long time until mmvec2 gets out.
The CV err is often quite high due to the MS intensities - as long as it is
substantially smaller than the average MS values, that should be ok.

**Comment by afvrbanac** [comment]
Ah okay, makes sense!
