### ISSUE TITLE
Nan in summary histogram for: qUbias_1 (was also qUmain or qVmain)

### ISSUE THREAD

**Issue by tgroth97** [biocore/mmvec#149]
When trying to run mmvec through qiime, I repeatedly got errors stating that there was a Nan in summary histogram. I was able to avoid the error by increasing the summary interval but then when trying to observe the model on tensor flow, there were no data points on the graphs. See an example of one of the error messages below.

[mmvec_error.txt](https://github.com/biocore/mmvec/files/5320033/mmvec_error.txt)

**Comment by mortonjt** [comment]
gotcha - yea increasing the summary interval won't help.

What does your table look like? Are there samples with no reads, or taxa with no reads?
Have you tried to decrease the learning rate? (i.e. 1e-4 for instance).

**Comment by tgroth97** [comment]
I just checked and I wasn't able to find any NaNs within either of my
tables. I've attached the tables in case you want to take a look for
yourself.

I did try decreasing the learning rate to 1e-4, 1e-10, and 1e-15, but each
time I still did receive an error message.

Tobin

**Comment by mortonjt** [comment]
Its not nans - its zeros.  If there are samples with 0 reads, or taxa with 0 reads, then such errors could arise.
Also, what is your command and input dimensions? How many taxa / metabolites are there and how many samples?
Have you made sure that all of your samples are matching?

When your command doesn't throw an error, what does the resulting ranks file look like?

And just as a sanity check, were you able to run the tutorials? (just to make sure your install is kosher).

**Comment by tgroth97** [comment]
I was able to identify a few metabolites that have 0 reads as well as a
good number of microbes that have 0 reads. Would it be best to have those
removed?

For the metabolite file there are 171 samples, 985 features. For the
microbes there are 171 samples and 5709 features. I ensured that the
samples between the two tables are indeed matching.

When I increase the summary-interval to 60 and use default parameters, the
ranks.qzv file (after using metadata tabulate on ranks.qza) shows all the
microbes and metabolites but every table entry is blank.

I was able to run the tutorial using my machine, and the ranks.qzv file was
full of all the features and the table was populated with numbers (unlike
my output table).

**Comment by mortonjt** [comment]
good, so your install is fine.  Try removing those features and rerun --
something is probably funky going on with your inputs.

**Comment by tgroth97** [comment]
After I removed the features with 0 reads, I was able to successfully run
mmvec! Both the ranks file as well as generating the biplot using emperor
worked. Now just comes the fun of adjusting parameters to improve the
model. Thanks for your help and suggestions!

Tobin

**Comment by mortonjt** [comment]
Great!
