### ISSUE TITLE
Error from biom table in wrong orientation and some manual suggestions

### ISSUE THREAD

**Issue by MilouArts** [biocore/mmvec#153]
I wanted to let you all know that I ran into an error and it was not clear to me what was wrong.
Jamie already let me know it was probably the issue that the rows and columns were swapped (and that was indeed the case!)

and before I put in the error code some suggestions, as i'm not familiar with qiime and very limited with python, so I'm running into a lot of things that are not clear for a not advanced user:

- It is not obvious if this program is run with python 2 or 3
- which packages are required and which versions
- do you need a .biom table in a json or hdf5 format?
- and what the orientation should be of the biom tables.

also, i'm getting alot of warnings tahat something from tensorflow is deprecated.

Super cool tool!
Thanks,
Milou

error:
/opt/biolinux/anaconda3/envs/qiime2-2020.6/lib/python3.6/site-packages/biom/table.py:4068: FutureWarning: SparseDataFrame is deprecated and will be removed in a future version.
Use a regular DataFrame whose columns are SparseArrays instead.

See http://pandas.pydata.org/pandas-docs/stable/user_guide/sparse.html#migrating for more.

  return constructor(mat, index=index, columns=columns)
/opt/biolinux/anaconda3/envs/qiime2-2020.6/lib/python3.6/site-packages/pandas/core/sparse/frame.py:257: FutureWarning: SparseSeries is deprecated and will be removed in a future version.
Use a Series with sparse values instead.

    >>> series = pd.Series(pd.SparseArray(...))

See http://pandas.pydata.org/pandas-docs/stable/user_guide/sparse.html#migrating for more.

  sparse_index=BlockIndex(N, blocs, blens),
/opt/biolinux/anaconda3/envs/qiime2-2020.6/lib/python3.6/site-packages/pandas/core/generic.py:4583: FutureWarning: SparseSeries is deprecated and will be removed in a future version.
Use a Series with sparse values instead.

    >>> series = pd.Series(pd.SparseArray(...))

See http://pandas.pydata.org/pandas-docs/stable/user_guide/sparse.html#migrating for more.

  return self._constructor(new_data).__finalize__(self)
/opt/biolinux/anaconda3/envs/qiime2-2020.6/lib/python3.6/site-packages/pandas/core/sparse/frame.py:854: FutureWarning: SparseDataFrame is deprecated and will be removed in a future version.
Use a regular DataFrame whose columns are SparseArrays instead.

See http://pandas.pydata.org/pandas-docs/stable/user_guide/sparse.html#migrating for more.

  default_kind=self._default_kind,
/opt/biolinux/anaconda3/envs/qiime2-2020.6/lib/python3.6/site-packages/pandas/core/frame.py:3471: FutureWarning: SparseSeries is deprecated and will be removed in a future version.
Use a Series with sparse values instead.

    >>> series = pd.Series(pd.SparseArray(...))

See http://pandas.pydata.org/pandas-docs/stable/user_guide/sparse.html#migrating for more.

  return klass(values, index=self.index, name=items, fastpath=True)
/opt/biolinux/anaconda3/envs/qiime2-2020.6/lib/python3.6/site-packages/pandas/core/sparse/frame.py:785: FutureWarning: SparseDataFrame is deprecated and will be removed in a future version.
Use a regular DataFrame whose columns are SparseArrays instead.

See http://pandas.pydata.org/pandas-docs/stable/user_guide/sparse.html#migrating for more.

  return self._constructor(new_arrays, index=index, columns=columns).__finalize__(
/opt/biolinux/anaconda3/envs/qiime2-2020.6/lib/python3.6/site-packages/pandas/core/ops/__init__.py:1641: FutureWarning: SparseSeries is deprecated and will be removed in a future version.
Use a Series with sparse values instead.

    >>> series = pd.Series(pd.SparseArray(...))

See http://pandas.pydata.org/pandas-docs/stable/user_guide/sparse.html#migrating for more.

  return self._constructor(new_values, index=self.index, name=self.name)
/opt/biolinux/anaconda3/envs/qiime2-2020.6/lib/python3.6/site-packages/pandas/core/sparse/frame.py:339: FutureWarning: SparseDataFrame is deprecated and will be removed in a future version.
Use a regular DataFrame whose columns are SparseArrays instead.

See http://pandas.pydata.org/pandas-docs/stable/user_guide/sparse.html#migrating for more.

  default_fill_value=self.default_fill_value,
/opt/biolinux/anaconda3/envs/qiime2-2020.6/lib/python3.6/site-packages/pandas/core/generic.py:5884: FutureWarning: SparseSeries is deprecated and will be removed in a future version.
Use a Series with sparse values instead.

    >>> series = pd.Series(pd.SparseArray(...))

See http://pandas.pydata.org/pandas-docs/stable/user_guide/sparse.html#migrating for more.

  return self._constructor(new_data).__finalize__(self)
/opt/biolinux/anaconda3/envs/qiime2-2020.6/lib/python3.6/site-packages/pandas/core/generic.py:3606: FutureWarning: SparseDataFrame is deprecated and will be removed in a future version.
Use a regular DataFrame whose columns are SparseArrays instead.

See http://pandas.pydata.org/pandas-docs/stable/user_guide/sparse.html#migrating for more.

  result = self._constructor(new_data).__finalize__(self)
Traceback (most recent call last):
  File "/opt/biolinux/anaconda3/envs/qiime2-2020.6/bin/mmvec", line 233, in <module>
    mmvec()
  File "/opt/biolinux/anaconda3/envs/qiime2-2020.6/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/opt/biolinux/anaconda3/envs/qiime2-2020.6/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/opt/biolinux/anaconda3/envs/qiime2-2020.6/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/biolinux/anaconda3/envs/qiime2-2020.6/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/biolinux/anaconda3/envs/qiime2-2020.6/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/opt/biolinux/anaconda3/envs/qiime2-2020.6/bin/mmvec", line 125, in paired_omics
    min_samples=min_feature_count)
  File "/opt/biolinux/anaconda3/envs/qiime2-2020.6/lib/python3.6/site-packages/mmvec/util.py", line 161, in split_tables
    sample_ids = set(np.random.choice(microbes_df.index, size=num_test))
  File "mtrand.pyx", line 900, in numpy.random.mtrand.RandomState.choice
ValueError: 'a' cannot be empty unless no samples are taken
(qiime2-2020.6) [marts@no73 ~]$

**Comment by mortonjt** [comment]
Hi @MilouArts , see below for your questions

1. Everything is in Python 3
2. The package versions are all specified in the [setup.py](https://github.com/biocore/mmvec/blob/master/setup.py) and the [conda-forge recipe](https://github.com/conda-forge/mmvec-feedstock/blob/master/recipe/meta.yaml).  The install instructions should automatically allow you handle this.
3. hdf5
4. I'd refer to the documentation on https://biom-format.org/.  By default, they take in the rows as observation (i.e. OTUs , metabolites, etc) and columns as samples.  If you need to transpose your tables, you can run the following code

```python
from biom import load_table, Table
from biom.util import biom_open
table = load_table('<your biom table>')
data = np.array(table.matrix_data.to_dense()).T
samples = table.ids(axis='observation')
features = table.ids(axis='sample')
new_table = Table(data, features, samples)
with biom_open('corrected_table.biom', 'w') as f:
    new_table.to_hdf5(f, 'transposed)
```

**Comment by lindsval** [comment]
Hi @MilouArts, 

At the very end of your post, I see that you have a similar error as me. Did you ever figure out the error: "ValueError: 'a' cannot be empty unless no samples are taken". I'm getting that after running the paired omics command. Wondering if its a formatting issue or something else. 

Thanks!

**Comment by MilouArts** [comment]
Hey @lindsval 

It was indeed the formatting issue!
so both files need to have the same samples [with identical names ] as columns, 
therfore every row is either a different microbe or metabolite (does this make sense? =) )

Hope this helps!

**Comment by lindsval** [comment]
@MilouArts 

Thank you!! I found my mistake with formatting. Appreciate it!

**Comment by mortonjt** [comment]
Sounds like this problem is resolved!  I'm going to close this issue for now.
