### ISSUE TITLE
ranks.qza file for heatmap

### ISSUE THREAD

**Issue by MilouArts** [biocore/mmvec#154]
Hey!

To create the heatmap a ranks.qza file is used as an input file,
however, I can't find/see where it is created following the README.md.
there is a ranks.text file created when running mmvec without qiime.

I did make a heatmap once using the conditionals.qza as an input file, I did get a heatmap out of it, but I'm not sure if it is showing what the ranks file is supposed to show.

are the ranks.qza and the conditionals.qza the same file or are they not interchangeable for making the heatmap? if not, how do I create the ranks.qza file?

**Comment by lindsval** [comment]
Hi  @MilouArts, 

Did ever figure out how to do this? I am wondering the same... 

Val

**Comment by mortonjt** [comment]
Hi @MilouArts , @lindsval , I'm unclear exactly what the question is -- we have documentation describing the contents of the heatmap as co-occurrence probabilities.  More details help me give an informed answer.

**Comment by lindsval** [comment]
Hi, 

So in order to create the heatmap, there is the input file "ranks.qza", however, I think we were both asking how to generate that ranks.qza file as I didn't see anywhere in the code before that where that file might be generated. 

Do we need to manually create the ranks.qza file from the conditionals.tsv file? i.e, manually go through an rank them by the log conditional probabilities?

Thanks, 
Val

**Comment by mortonjt** [comment]
got it - if you are running the standalone version and want to import that into qiime, its
```
qiime tools import --input-path conditionals.tsv --output-path ranks.qza --type FeatureData[Conditional]
```

Note that ranks.qza is produced by `qiime mmvec paired-omics` - you only run into this issue if you are going back and forth between the qiime2 implementation and the standalone.

**Comment by MilouArts** [comment]
Hey Jamie (and Val)

It is also a "problem" / not clear when only using the qiime2 implementation.

If you use the qiime implementation and follow the README steps/manual you create 3 files running mmvec ->  
- conditionals.qza, 
- conditionals_biplot.qza and 
- model_stats.  
(correct me if I'm wrong)

But then when the manual comes to the step of making the heatmap, it uses a ranks.qza as an input file. but that is not created during the previous steps

Your answer implies that ranks.qza is the same file as conditionals.qza
however, how I normally understand it is that a conditional probability is something different than the ranking from the ML


p.s.
the only time there is a ranks file created (which has "ranks" in the file name), is with the standalone version (latent_dim_3_input_prior_1.00_output_prior_1.00_beta1_0.90_beta2_0.95_ranks.txt) which is causing confusion.
in the standalone version there is not a conditionals.tsv created.

**Comment by MilouArts** [comment]
So @mortonjt 

is the conditionals.qza created by the qiime mmvec, the same file as ranks.qza that is the input file for the heatmap?

if no, what is the difference?

**Comment by mortonjt** [comment]
yes they are the same
