### ISSUE TITLE
paired_omics error - 'arm_the_gpu'

### ISSUE THREAD

**Issue by lindsval** [biocore/mmvec#155]
Hi, 

I am receiving the below error while trying to run the example mmvec data. I have been working with the mmvec plug-in through Qiime2. mmvec and tensorflow have both been installed in the environment.

I am able to run both of these commands: 
qiime tools import \
        --input-path otus_nt.biom \
        --output-path otus_nt.qza \
        --type FeatureTable[Frequency]
qiime tools import \
        --input-path lcms_nt.biom \
        --output-path lcms_nt.qza \
        --type FeatureTable[Frequency]

but when I try to run: 
qiime mmvec paired-omics \
        --i-microbes otus_nt.qza \
        --i-metabolites lcms_nt.qza \
        --p-summary-interval 1 \
        --output-dir model_summary

I receive this error: 
"Plugin error from mmvec: paired_omics() got an unexpected keyword argument 'arm_the_gpu'"

Is there a step I have missed or something I need to change/install before running?

Thanks, 
Val

**Comment by mortonjt** [comment]
hmm - that's very disturbing.  Can you confirm which version of mmvec you are using?  Also does the standalone version work for you?

I'll try to reproduce the error as soon as I get back to the keyboard...

**Comment by lindsval** [comment]
Hi, 

I can confirm I am using mmvec: 1.0.6 with QIIME2-2019.10

I have not tried the standalone version, as I am more comfortable using QIIME2. I can give it a go, though.

Thanks, 
Val

**Comment by mortonjt** [comment]
Hi @lindsval , I'm having some trouble reproducing this error -- do you see the same issue when you upgrade to qiime2-2020.6?

**Comment by lindsval** [comment]
Upgrading to qiime2-2020.6 fixed the issue! Thanks for the help.

**Comment by mortonjt** [comment]
Yay. That’s awesome!
