### ISSUE TITLE
heatmap   change "--p-x-labels " size

### ISSUE THREAD

**Issue by iratxezarra** [biocore/mmvec#156]
Hello developpers!

I am able to successfully create several heatmaps, but i am working with aprox. 80-90  metabolites  and I can't find a way of displaying all the their names in the x axis. Is there a way of decreasing the size of the labels?

Also, I was not able to find additional information regarding which is the difference between conditional.qza and ranks.qza, ( if there is any).

Thanks so much for the help and for developing  such a nice tool!

**Comment by mortonjt** [comment]
Hi @iratxezarra thank you for your interest.

The plotting abilities for mmvec are a bit limited, since its not a plotting library.  But you can always export your data to be read in Python / R; you can convert your conditional.qza / ranks.qza to a text file as follows
```
qiime tools export --input-path ranks.qza --output-path ranks-text
```
P.S. conditional.qza and ranks.qza are likely the same type; you can check with `qiime tools peek`

**Comment by iratxezarra** [comment]
Thanks for answering!
i will try to create the heatmaps in R then!
conditional.qza and rank.qza are same type, yes, but is it the same
information but sorted, or what is the difference between the numbers that
appear in both documents?

Iratxe Zarraonaindia Martinez
Maria Goyri, Lab. 1.08. (Applied genomics and Bioinformatics)
University of the Basque Country (UPV/EHU)
Bº Sarriena s/n 48940, Leioa; Bilbao; Spain
Tfno: +34-946015510
E-mail: ***@***.***, ***@***.***
http://www.genomic-resources.eu/

**Comment by mortonjt** [comment]
I'm not exactly which files you are referring to, since the filenames are specified by you.
They should both output mean-centered log conditional probabilities. If you want raw conditional probabilities, see https://github.com/biocore/mmvec/issues/93
