### ISSUE TITLE
Error: QIIME 2 has no plugin/command named 'mmvec'.

### ISSUE THREAD

**Issue by ssorgatem** [biocore/mmvec#157]
Installation doesn't seem to work in a qiime2 2021-2 conda environment

**Comment by mortonjt** [comment]
That is expected due to tensorflow incompatibility.
The last working qiime2 version was 2020.6
Unfortunately we’re going to have to do a complete rewrite ...

**Comment by ssorgatem** [comment]
Well, somehow I got it working installing it from conda and then overwriting it with pip installing from this repo.

**Comment by mortonjt** [comment]
See this [issue](https://github.com/biocore/mmvec/issues/150).  In the process of overwriting the default qiime2 packages, you probably downgraded numpy, which will work for mmvec, but I can't speak for the other qiime2 packages.
