### ISSUE TITLE
ranks with full taxonomic hierarqui rather than featureid

### ISSUE THREAD

**Issue by iratxezarra** [biocore/mmvec#158]
Hi 

Is there a way to include the full hierarchical taxonomic names in the rank.qza file? ( rather than just the feature_id itself?) 
if i convert this rank file into qzv, then I visualize it in qiime view, and save them as .tsv  I do not have a way to know which taxa they belong to...

thanks in advance

**Comment by mortonjt** [comment]
They are both metadata files, so it should be doable.
You can definitely combine the taxonomy file with the metadata, but I don’t
know of a qiime2 command that do this.

It’ll likely require something as follows in python

import qiime2
import pandas as pd
taxa = qiime2.Artifact.load(“taxonomy.qza”).view(pd.DataFrame)
ranks = qiime2.Artifact.load(“ranks.qza”).view(pd.DataFrame)
combined = pd.concat((ranks.T, taxa), axis=1)
combined.to_csv(“combined.txt”, sep=‘\t’)

In this way, you can view in excel, but it’ll be hard to sort the molecules
...

**Comment by iratxezarra** [comment]
Great, Thanks so much. I will give it a try!
:-)
Iratxe Zarraonaindia Martinez
Maria Goyri, Lab. 1.08. (Applied genomics and Bioinformatics)
University of the Basque Country (UPV/EHU)
Bº Sarriena s/n 48940, Leioa; Bilbao; Spain
Tfno: +34-946015510
E-mail: ***@***.***, ***@***.***
http://www.genomic-resources.eu/
