### ISSUE TITLE
help with heatmap conditionals to create ranks.qza file

### ISSUE THREAD

**Issue by CarlaCristinaUranga** [biocore/mmvec#161]
Hi I am having trouble creating the ranks.qza file for the heatmap, I get this error:

(qiime2) curanga@x86_64-apple-darwin13 bioinf_job % qiime tools import \
  --input-path model_4/conditionals.txt \
  --type 'FeatureTable[Conditional]' \
  --output-path ranks.qza
Traceback (most recent call last):
  File "/Users/curanga/opt/anaconda3/envs/qiime2/lib/python3.6/site-packages/q2cli/builtin/tools.py", line 158, in import_data
    view_type=input_format)
  File "/Users/curanga/opt/anaconda3/envs/qiime2/lib/python3.6/site-packages/qiime2/sdk/result.py", line 213, in import_data
    output_dir_fmt = pm.get_directory_format(type_)
  File "/Users/curanga/opt/anaconda3/envs/qiime2/lib/python3.6/site-packages/qiime2/sdk/plugin_manager.py", line 313, in get_directory_format
    % semantic_type)
TypeError: Semantic type FeatureTable[Conditional] does not have a compatible directory format.

An unexpected error has occurred:

  Semantic type FeatureTable[Conditional] does not have a compatible directory format.

See above for debug info.
(qiime2) curanga@x86_64-apple-darwin13 bioinf_job % 

I am not sure if it is because you have to create a .biom file first or what is wrong. I have attached my conditionals file. So these are probabilities, but do they need to be converted to % values? Thank you!

[conditionals.txt](https://github.com/biocore/mmvec/files/6429309/conditionals.txt)

**Comment by mortonjt** [comment]
It looks like a small typo, it should be `FeatureData` instead of `FeatureTable` :)

```
qiime tools import
--input-path model_4/conditionals.txt
--type 'FeatureData[Conditional]'
--output-path ranks.qza
```
