### ISSUE TITLE
Why 13 metabolites as ground truth in soil dataset? 

### ISSUE THREAD

**Issue by wanglu2014** [biocore/mmvec#164]
When we were evaluatiing mmvec on soil metabolites, we found that no direct description of 13 metabolites in the original data source (DOI: 10.1038/s41467-017-02356-9).  Could you kindly describe why did you choose those metabolites as ground truth in mmvec study?
Thank you for your help!

**Comment by mortonjt** [comment]
See Figure 3 in this paper https://pubmed.ncbi.nlm.nih.gov/29296020/

**Comment by wanglu2014** [comment]
> See Figure 3 in this paper https://pubmed.ncbi.nlm.nih.gov/29296020/
There were 14 metabolites that have connections with Microcoleus sp in Fig3.
