### ISSUE TITLE
docs: specify abundance vs frequency 

### ISSUE THREAD

**Issue by LenaFloerl** [biocore/mmvec#174]
Hi, very minor question regarding the phrasing in the README on Input Data, it says: 

> Microbe abundance (.biom): A _relative abundance_ table with microbial species in rows and samples in columns.

but in qiime2 one passes a `FeatureTable[Frequency]` and I am not sure if  _frequency_ and _abundance_ can be used interchangeable in this context. Would you please specify?

Thanks for putting this great plugin together! 🚀 
Lena

**Comment by mortonjt** [comment]
CC @eboylen regarding semantic terminology.

Yes, as far as I'm aware, the two terms are interchangable
