### ISSUE TITLE
What's the threshod of p*n in the microbe and metabolite datasets? 

### ISSUE THREAD

**Issue by 12Hanyue** [biocore/mmvec#180]
I tried example datasets in the paper and ran the whole command successfully. But when I tried to use my data (10 samples, 400 metabolites, and 400 microbes), it didn't work. And I also tried to reduce the example dataset to the same sample size. It wasn't successful too.

**Comment by mortonjt** [comment]
10 samples is too small. I wouldnt expect it to work here

**Comment by 12Hanyue** [comment]
Thank you for your quick response! How many samples should the threshold be?

**Comment by mortonjt** [comment]
I havent been able to fit anything below 18 samples. Even then youd need to
bring down your latent dim to 1

**Comment by 12Hanyue** [comment]
Thank you so much for your help
