### ISSUE TITLE
Could nose + Cython be installed via conda instead?

### ISSUE THREAD

**Issue by tseemann** [biocore/mmvec#47]
I notice when i `pip install rhapsody` it manually installs these 3 packages:

`nose, rhapsody, Cython`

Just wondering if nose and Cython could be done via conda like the others?

**Comment by mortonjt** [comment]
Right, it should not be a problem to install those packages via conda.

**Comment by mortonjt** [comment]
Hi @tseemann thanks for raising this issue. We have a supported conda channel for mmvec [here](https://anaconda.org/conda-forge/mmvec). Please feel free to follow up if there are further installation issues.
