### ISSUE TITLE
q2 version and sample identifiers

### ISSUE THREAD

**Issue by jaybake5** [biocore/mmvec#60]
Hi Jamie,
After a couple months working on other projects, I've come back to our project where we want to look at correlations between the taxa in the oral microbiome and cytokine ("metabolite") concentrations (you helped Anna and I with this project using Songbird back in the fall).  I did a fresh install of rhapsody as of today.  I had an issue with the standalone version not responding after the progress bar was full, which I'll post as a separate issue.  I tried out the QIIME2 version with my data and actually got biplot.qza and ranks.qza output files, but when I tried to visualize the biplot, I got the following error:

Plugin error from emperor:

  None of the sample identifiers match between the metadata and the coordinates. Verify that you are using metadata and coordinates corresponding to the same dataset.

Debug info has been saved to /var/folders/rr/2hbbkrqs5mn86rnt2s4yywsr0003kj/T/qiime2-q2cli-err-hdt_bqk5.log

My sample id's definitely match with the metadata file, I tested them by doing DEICODE and the following Emperor plot with the same microbes.qza and metadata file, and it worked fine.

To try and debug this myself, I downloaded your CF dataset in knightlab-analyses/multiomic-cooccurences.  Same as with my data, I was able to get the biplot and ranks qza files, but I got the same error when trying to make the emperor plot using your metadata files:

qiime emperor biplot \
	--i-biplot biplot.qza \
	--m-sample-metadata-file sample-metadata.txt \
	--m-feature-metadata-file validated-molecules.txt \
	--o-visualization emperor.qzv
It looks like all the sample and feature ids match between the metadata and tables...any help you could provide would be greatly appreciated.  I see you're presenting on this to Rob and Pieter's meeting in a couple weeks, are you actually going to be in town?
Best,

Jon

**Comment by mortonjt** [comment]
The time out has to do with the cross validation - how long did it take
before you killed it?

Regarding emperor, I bet that has to do with the wrong metadata files. You
want to pass in metabolite information as samples and microbe information
as features. The confusion has to do with hacking emperor to perform a very
different task

**Comment by jaybake5** [comment]
Ok, thanks!  I got the q2 version working and have generated biplots.  Can you do anything with the ranks.qza output?  I was thinking maybe you could put it into Qurro or something as with Songbird but that doesn't seem to be the case (at least not yet).

For the standalone:  I left it going for at least an hour before I killed it, and this was for a job that took less than 1 minute to complete the rhapsody progress bar.  How long would you expect it to take?  Also, the Tensorboard for these standalone runs never actually generates a 'Scalar' tab...only a 'Graphs' tab with a map.  Meanwhile, with the q2 version I am getting nice cv_rmse and logloss plots...
Thanks!

**Comment by mortonjt** [comment]
On Tue, Jul 16, 2019, 8:59 PM Jonathon L. Baker <notifications@github.com>
wrote:

> Ok, thanks! I got the q2 version working and have generated biplots. Can
> you do anything with the ranks.qza output? I was thinking maybe you could
> put it into Qurro or something as with Songbird but that doesn't seem to be
> the case (at least not yet).
>

Yes, you can unzip that file and get a complete readout of the conditional
probabilities.

> For the standalone: I left it going for at least an hour before I killed
> it, and this was for a job that took less than 1 minute to complete the
> rhapsody progress bar. How long would you expect it to take? Also, the
> Tensorboard for these standalone runs never actually generates a 'Scalar'
> tab...only a 'Graphs' tab with a map. Meanwhile, with the q2 version I am
> getting nice cv_rmse and logloss plots...
> Thanks!
>

That is weird...

**Comment by mortonjt** [comment]
@jaybake5 a PR has been at #61, so the hangup issue will soon be addressed.

It'll be some time until the ranks can be plugged into qurro - but an example on how to parse those can be seen in that same PR with the soils dataset.

**Comment by mortonjt** [comment]
Hi @jaybake5 , has this issue been addressed?

**Comment by mortonjt** [comment]
HI @jaybake5 I'm going to close this issue; feel free to follow up if there are still outstanding issues.

**Comment by jonbakerlab** [comment]
Yep, this is all good.  Sorry I forgot to reply to that last message!
