### ISSUE TITLE
Obvious instability warnings

### ISSUE THREAD

**Issue by wasade** [biocore/mmvec#85]
The produced biplots can sometimes have surprising proportions explained, such that `axis 1 < axis 2 < axis 3` or where the proportion explained for an axis is > 100%. It would be nice if `mmvec` generated a warning when these scenarios are observed in the results and to suggest that the user may not want to use the output.

**Comment by mortonjt** [comment]
@wasade - do you have an explicit ordination results file that shows these wonky results?

I'm not able to reproduce these results - it'll be great if we could patch it before the next release.

**Comment by wasade** [comment]
Franck does -- unsure what his GH handle is, I'll follow up on the relevant email thread and ask him to provide context here.

**Comment by mortonjt** [comment]
ok, got the ordination file from Franck.  Below are the eigenvalues / proportion explained
```
Eigvals	3
0.3058593288174586	2.3895480775642652	9.001766424679664

Proportion explained	3
0.0010773261702244183	0.06575598584302014	0.9331666879867555
```
These values looks reasonable to me, but the emperor plot doesn't reflect this at all.
Below is the file.  Not sure why this is the case - I wonder if it has to do with the ordering of the eigenvalues in #86 . Let's try to knock out that issue first and see if this error remains.

CC @ElDeveloper just in case.

File is below
[latent_dim_3_input_prior_1.00_output_prior_1.00_beta1_0.85_beta2_0.90_ordination.txt](https://github.com/biocore/mmvec/files/3664483/latent_dim_3_input_prior_1.00_output_prior_1.00_beta1_0.85_beta2_0.90_ordination.txt)

**Comment by mortonjt** [comment]
Thanks @wasade @FranckLejzerowicz this should be addressed now.
