### ISSUE TITLE
Proportion explained is out of order: axis 1 < axis 2 < axis 3

### ISSUE THREAD

**Issue by wasade** [biocore/mmvec#86]
When visualizing biplots, the proportion explained for axis 1 is less than the proportion explained for axis 2, which is less than the proportion explained for axis 3. An example of this can be found in the screenshot below.

Typically, users of EMPeror are accustom to interpreting axis 1 as explaining the most variation in the data. At present, this ordering reflects an inversion which may catch users off guard. 

![image-1](https://user-images.githubusercontent.com/474290/64628930-27aa9280-d3a7-11e9-9df6-b901349d31b7.png)

**Comment by mortonjt** [comment]
Yes, we will want to make sure that this is consistent with previous ordinations.  Adding to the version 1 agenda

**Comment by FranckLejzerowicz** [comment]
I would also document an issue that is that the proportions explained in the biplot are sometime >100%, e.g.
![Screenshot 2019-09-27 at 2 07 54 PM](https://user-images.githubusercontent.com/29630133/65803439-74c28e80-e133-11e9-8c2e-420579a39073.png)

and when you edit the ordinations but re-ordering
``
Proportion explained	3
0.0010773261702244183	0.06575598584302014	0.9331666879867555
 ```
to
``
Proportion explained	3
0.9331666879867555	0.06575598584302014	0.0010773261702244183
 ```
It display the proportions explained correctly.
<img width="562" alt="Screenshot 2019-09-27 at 2 26 59 PM" src="https://user-images.githubusercontent.com/29630133/65803581-ccf99080-e133-11e9-8a03-b1a79bf27774.png">

However, you may want to the check the consistency of the coordinates along these axes...

Thanks!

**Comment by mortonjt** [comment]
Thanks @wasade @FranckLejzerowicz this should be addressed now.
