### ISSUE TITLE
missing index.html

### ISSUE THREAD

**Issue by cameronmartino** [biocore/mmvec#90]
using the current conda installation I get the following for the heatmap function:

```python
FileNotFoundError: [Errno 2] No such file or directory: 
'/Users/ ... /assets/index.html'
``` 
I then downloaded and added the asset + index file and everything ran fine. 

Seems like for some reason it was just not packaged with the newest conda install.

**Comment by mortonjt** [comment]
Weird... Just to confirm, what command did you use? Was this the Readme
install?

That may have to do with the visualizations - will need to double check

**Comment by cameronmartino** [comment]
yup Readme conda install:

```bash 
conda install mmvec -c conda-forge
```

**Comment by mortonjt** [comment]
ok, I'm able to reproduce the problem

```
Plugin error from mmvec:

  [Errno 2] No such file or directory: '/Users/jmorton/miniconda3/envs/qiime2-2019.7/lib/python3.6/site-packages/mmvec/q2/assets/index.html'

Debug info has been saved to /var/folders/ds/bxbcw9055535jv1689xnhhfc0001bm/T/qiime2-q2cli-err-uq8wsatb.log
```

@nbokulich do you have some insights into this? It's not clear to me why the assets folder isn't properly being copied

https://github.com/biocore/mmvec/blob/master/mmvec/q2/assets/index.html

**Comment by ElDeveloper** [comment]
Looks like there's a missing entry in setup.py for the package_data keyword.
